# Generated by Django 5.2.7 on 2025-10-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='children_images/')),
                ('address', models.TextField()),
                ('details', models.TextField()),
                ('person_name', models.CharField(max_length=100)),
                ('person_contact', models.CharField(max_length=15)),
                ('is_safe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
