# Generated by Django 5.2.7 on 2025-10-02 06:20

import NGO.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ngoinfo',
            managers=[
                ('objects', NGO.models.NGOUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='ngoinfo',
            name='username',
        ),
    ]
